{
	"Service": "/iLibrary/Services/iLibraryService.service",
	"DefiningRequests": [
	{
		"Name": "BookSet",
		"Query": "BookSet"
	},
	{
		"Name": "LendingSet",
		"Query": "LendingSet"
	},
	{
		"Name": "UserSet",
		"Query": "UserSet"
	}
],
	"_Type": "Action.Type.OfflineOData.Download",
	"ActionResult": {
		"_Name": "sync"
	},
	"OnFailure": "/iLibrary/Actions/Service/SyncFailureMessage.action"
}